apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-operator-configmap
  namespace: giantswarm
data:
  config.yaml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      kubernetes:
        incluster: true
