apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ingress-operator
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - core.giantswarm.io
    resources:
      - ingressconfigs
    verbs:
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - ingress-operator-pull-secret
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - update
  - nonResourceURLs:
      - "/"
      - "/healthz"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ingress-operator
subjects:
  - kind: ServiceAccount
    name: ingress-operator
    namespace: giantswarm
roleRef:
  kind: ClusterRole
  name: ingress-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ingress-operator-psp
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - ingress-operator-psp
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ingress-operator-psp
subjects:
  - kind: ServiceAccount
    name: ingress-operator
    namespace: giantswarm
roleRef:
  kind: ClusterRole
  name: ingress-operator-psp
  apiGroup: rbac.authorization.k8s.io